### ISSUE TITLE
isl_ctx.c:293: isl_ctx not freed as some objects still reference it

### ISSUE THREAD

**Issue by sheenisme** [PollyLabs/ppcg#1]
Hello, when I try to change the ppcg code, no matter how I modify it, I will always encounter this problem-"isl_ctx.c:293: isl_ctx not freed as some objects still reference it". So I want to ask how I can locate the problem and what should I pay attention to in isl_ctx. Look forward to your reply, thank you.

**Comment by Meinersbur** [comment]
Every ISL object you create must also be freed using the corresponding `*_free` function. `isl_ctx` keeps a counter of how many objects has been allocated and how many has been freed. If it is not 0 when the `isl_ctx` is released, it will through that error.

Every ISL function that returns `__isl_give` "creates" and object that need to be released, e.g. `isl_set_intersect`. Any parameter annotated with `__isl_take` releases the object for you so you don't have to do it.

Note the main point of contact is [isl-development](https://groups.google.com/g/isl-development) mailing list. That's how you can reach the main author of PPCG/ISL.

**Comment by sheenisme** [comment]
Thank you very much for your reply. I noticed the cautions you mentioned about `isl_ctx` after reading the isl manual too. I also did my best to correctly allocated and freed objects. But I still don't know where there are errors. I want to know if there are any interfaces or strategies that can help me better locate bugs. Look forward to receiving your reply.
